import { Plane, CarFront, BriefcaseBusiness, MapPinned, Landmark } from 'lucide-react';

export const business = {
  name: 'Dutch Taxi Transfers',
  regionTagline: 'AMSTERDAM · SCHIPHOL · THE NETHERLANDS',
  phoneDisplay: '+31 20 308 6885',
  phoneLink: 'tel:+31203086885',
  supportCopy: '24/7 Customer Support',
  hero: {
    eyebrow: 'RELIABLE • PROFESSIONAL • ON TIME',
    headlineLead: 'Amsterdam Taxi &',
    headlineAccent: 'Airport Transfers',
    description: 'Professional taxi and private transfer services for Schiphol Airport, Amsterdam and destinations across the Netherlands. Travel comfortably, arrive on time and book with confidence.',
    primaryAction: 'Book Your Ride',
    secondaryAction: 'Get a Quote',
    assurance: 'Professional transport for business, airport and private travel.',
  },
  nav: [
    { label: 'Home', href: '/' },
    { label: 'Services', href: '/services' },
    { label: 'Destinations', href: '/destinations' },
    { label: 'Pricing', href: '/pricing' },
    { label: 'About Us', href: '/about' },
    { label: 'Blog', href: '/blog' },
    { label: 'Contact', href: '/contact' },
  ],
  booking: {
    eyebrow: 'YOUR JOURNEY, MADE SIMPLE',
    title: 'Quick Book Your Transfer',
    fromLabel: 'From',
    fromPlaceholder: 'Pickup location',
    toLabel: 'To',
    toPlaceholder: 'Destination',
    dateLabel: 'Date & time',
    passengersLabel: 'Passengers',
    luggageLabel: 'Luggage',
    submitLabel: 'Check Price',
    handoffMessage: 'This site does not calculate fares or place reservations. Your trip details stay on this page.',
    handoffAction: 'Call to check price',
    footnote: 'No fare or reservation is confirmed here. Call to verify your fare and book.',
  },
  servicesIntroduction: {
    eyebrow: 'MOVE WITH PURPOSE',
    headlineLead: 'One trusted partner.',
    headlineAccent: 'Every kind of journey.',
    description: 'From the runway to the boardroom, count on professional transport for business, airport and private travel.',
  },
  services: [
    { title: 'Airport Transfers', description: 'Schiphol ↔ Amsterdam & beyond', Icon: Plane },
    { title: 'Amsterdam Taxi', description: 'City rides, hotels, stations & more', Icon: CarFront },
    { title: 'Private Transfers', description: 'Your journey, your way', Icon: MapPinned },
    { title: 'Business Transportation', description: 'Professional & discreet', Icon: BriefcaseBusiness },
    { title: 'Day Trips', description: 'Zaanse Schans, Giethoorn, Keukenhof & more', Icon: Landmark },
  ],
  trust: {
    eyebrow: 'THE DUTCH TAXI DIFFERENCE',
    titleLead: 'Trusted by Travellers',
    titleAccent: '& Businesses.',
    description: 'Good journeys begin with people who understand the value of your time. We serve Amsterdam, Schiphol and destinations throughout the Netherlands.',
    contactAction: 'Speak with our team',
    serviceCardTitle: 'Service you can rely on',
    availabilityLabel: 'Available',
    availability: '24 hours / 7 days',
    reviewsEyebrow: 'GOOGLE REVIEWS',
    pendingReviewCopy: 'Every journey deserves a thoughtful review.',
    reviewsAction: 'View on Google',
    reviewDisclosure: 'Review ratings will appear here once verified.',
    reviewsUrl: 'https://www.google.com/search?q=Dutch+Taxi+Transfers+Amsterdam+reviews',
  },
  trustPoints: [
    'Fixed & transparent pricing',
    'Professional drivers',
    'Flight monitoring & on-time pickup',
    '24/7 customer support',
  ],
  footerCopy: 'Professional transport for business, airport and private travel.',
  footerRegion: 'Amsterdam · Schiphol · The Netherlands',
};

// Populate only after the business supplies verified review data.
export const reviewSummary: { rating?: string; count?: string; source?: string } = {};
